# Generated by Django 5.0.5 on 2024-05-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuApp', '0004_alter_item_status_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
